kind: Service                             
apiVersion: v1
metadata:
  name: mrdevops
  labels:
    app: mrdevops
spec:
  ports:
    - port: 8080                  # Containers port exposed                
      targetPort: 80              # Pods Port      
      nodePort: 31200             
  selector:
    app: mrdevops                 # Apply this service to any pods which has the specific label   
  type: LoadBalancer              # Specifies te service type i.e. ClusterIP or NodePort